// core/styles/fantasyStyles.ts

import type { StyleConfig } from '../styles.config';

export const FANTASY_STYLE_CONFIGS: StyleConfig[] = [
  {
    id: 'futuristic',
    name: 'Futuriste (Hologramme Cyberpunk)',
    era: '2150',
    mode: 'both',
    bearing: 0,
    bordersVisibleByDefault: true,
    mapStyleUrl: 'https://basemaps.cartocdn.com/gl/dark-matter-gl-style/style.json',
    texture: {
      blendMode: 'screen',
      opacity: 0.15,
      borderColor: '#00f3ff',
      borderWidth: 2,
    },
    scanlines: {
      enabled: true,
      speed: 2,
      opacity: 0.12,
      color: '#00f3ff',
    },
    glowPulse: {
      enabled: true,
      color: '#00f3ff',
      interval: 3000,
    },
    glassmorphism: true,
    fontFamily: '"Orbitron", "Rajdhani", sans-serif',
    decorativeBorder: 'circuit',
    labelLanguage: 'en',
    mapPaintOverrides: {
      background: '#0a0e17',
      water: '#05182c',
      landcover: '#111b2b',
    },
  },
  {
    id: 'futuristic_cyberpunk_neon',
    name: 'Futuriste (Cyberpunk Néon)',
    era: '2180',
    mode: 'both',
    bearing: 0,
    bordersVisibleByDefault: true,
    mapStyleUrl: 'https://basemaps.cartocdn.com/gl/dark-matter-gl-style/style.json',
    texture: {
      blendMode: 'screen',
      opacity: 0.2,
      borderColor: '#ff007f',
      borderWidth: 2,
    },
    scanlines: {
      enabled: true,
      speed: 3,
      opacity: 0.15,
      color: '#ff007f',
    },
    fontFamily: '"Orbitron", sans-serif',
    decorativeBorder: 'circuit',
    labelLanguage: 'en',
  },
  {
    id: 'futuristic_space_opera',
    name: 'Futuriste (Space Opera Stellaire)',
    era: '3000',
    mode: 'both',
    bearing: 0,
    bordersVisibleByDefault: true,
    mapStyleUrl: 'https://basemaps.cartocdn.com/gl/dark-matter-gl-style/style.json',
    texture: {
      blendMode: 'screen',
      opacity: 0.1,
    },
    fontFamily: '"Rajdhani", sans-serif',
    decorativeBorder: null,
    labelLanguage: 'en',
  },
  {
    id: 'tolkien_high_fantasy',
    name: 'Tolkien (High Fantasy Épique)',
    era: 'Troisième Âge d\'Arda',
    mode: 'both',
    bearing: 0,
    bordersVisibleByDefault: false,
    mapStyleUrl: 'https://basemaps.cartocdn.com/gl/positron-gl-style/style.json',
    texture: {
      blendMode: 'multiply',
      opacity: 0.45,
      svgFilterId: 'parchment-coarse',
      radialVignette: { inner: 'transparent', outer: 'rgba(60,35,15,0.6)' },
      noisePattern: { frequency: 0.05, octaves: 4 },
      borderColor: '#5C3A21',
      borderWidth: 8,
    },
    rhumbLines: {
      enabled: true,
      centers: [[0, 0], [45, -20]],
      rayCount: 16,
      colors: ['#5C3A21', '#8B0000', '#2E8B57'],
      radiusKm: 4000,
      lineWidth: 1.0,
      labels: ['Manwë (Nord)', 'Ulmo (Ouest)', 'Aulë (Est)', 'Oromë (Sud)'],
    },
    fontFamily: '"Cinzel Decorative", "Georgia", serif',
    decorativeBorder: 'rinceaux',
    labelLanguage: 'la',
    mapPaintOverrides: {
      background: '#e8dfcb',
      water: '#123a5c',
      landcover: '#8a9a6e',
    },
  },
  {
    id: 'tolkien_light_fantasy',
    name: 'Tolkien (Light Fantasy Féerique)',
    era: 'Valinor & Lorien',
    mode: 'both',
    bearing: 0,
    bordersVisibleByDefault: false,
    mapStyleUrl: 'https://basemaps.cartocdn.com/gl/positron-gl-style/style.json',
    texture: {
      blendMode: 'multiply',
      opacity: 0.25,
      svgFilterId: 'paper-smooth',
      radialVignette: { inner: 'transparent', outer: 'rgba(100,120,80,0.3)' },
      borderColor: '#8A9A5B',
      borderWidth: 4,
    },
    fontFamily: '"Cinzel", "Georgia", serif',
    decorativeBorder: 'rinceaux',
    labelLanguage: 'en',
    mapPaintOverrides: {
      background: '#f4f0e6',
      water: '#2d6b7a',
      landcover: '#d8d2b8',
    },
  },
  {
    id: 'tolkien_dark_fantasy',
    name: 'Tolkien (Dark Fantasy Terres Maudites)',
    era: 'Mordor & Angmar',
    mode: 'both',
    bearing: 0,
    bordersVisibleByDefault: false,
    mapStyleUrl: 'https://basemaps.cartocdn.com/gl/dark-matter-gl-style/style.json',
    texture: {
      blendMode: 'multiply',
      opacity: 0.6,
      svgFilterId: 'parchment-coarse',
      radialVignette: { inner: 'transparent', outer: 'rgba(20,0,0,0.8)' },
      borderColor: '#3a0000',
      borderWidth: 6,
    },
    fontFamily: '"Cinzel Decorative", serif',
    decorativeBorder: null,
    labelLanguage: 'la',
    mapPaintOverrides: {
      background: '#1a1816',
      water: '#0d0f14',
      landcover: '#3a3230',
    },
  },
  {
    id: 'realistic_satellite',
    name: 'Réaliste (Hypsométrie Naturelle & Océanique)',
    era: 'Moderne Scientifique',
    mode: 'both',
    bearing: 0,
    bordersVisibleByDefault: true,
    mapStyleUrl: 'https://basemaps.cartocdn.com/gl/positron-gl-style/style.json',
    texture: {
      blendMode: 'multiply',
      opacity: 0.1,
    },
    fontFamily: '"Inter", sans-serif',
    decorativeBorder: null,
    labelLanguage: 'fr',
  },
];
