// core/styles/realStylesContemporary.ts

import type { StyleConfig } from '../styles.config';

export const CONTEMPORARY_STYLE_CONFIGS: StyleConfig[] = [
  {
    id: 'colonial',
    name: 'Époque Contemporaine (Grandes Puissances — Atlas 1914)',
    era: '1914',
    mode: 'both',
    bearing: 0,
    bordersVisibleByDefault: true,
    mapStyleUrl: 'https://basemaps.cartocdn.com/gl/positron-gl-style/style.json',
    texture: {
      blendMode: 'multiply',
      opacity: 0.25,
      svgFilterId: 'engraving-copper',
      borderColor: '#5c3a21',
      borderWidth: 4,
    },
    terraIncognita: {
      enabled: true,
      regions: ['antarctica_interior', 'amazon_deep'],
      labels: ['TERRA INCOGNITA', 'EXPLORANDUM'],
    },
    empireColors: {
      british: '#d62728',
      french: '#1f77b4',
      portuguese: '#2ca02c',
      neutral: '#7f7f7f',
    },
    graticule: {
      enabled: false,
      step: 10,
      color: '#784421',
      opacity: 0.35,
      labelColor: '#784421',
    },
    fontFamily: '"Playfair Display", "Georgia", serif',
    decorativeBorder: null,
    labelLanguage: 'en',
    mapPaintOverrides: {
      background: '#f5eedc',
      water: '#cbe2ee',
      landcover: '#eee5d3',
    },
  },
  {
    id: 'contemporary_current',
    name: 'Contemporain (OpenStreetMap / Voyager Vectoriel)',
    era: '2024',
    mode: 'both',
    bearing: 0,
    bordersVisibleByDefault: true,
    mapStyleUrl: 'https://basemaps.cartocdn.com/gl/voyager-gl-style/style.json',
    texture: {
      blendMode: 'multiply',
      opacity: 0,
    },
    fontFamily: '"Inter", "Helvetica Neue", sans-serif',
    decorativeBorder: null,
    labelLanguage: 'fr',
    mapPaintOverrides: {
      background: '#f1f5f9',
      water: '#0284c7',
      landcover: '#e2e8f0',
    },
  },
  {
    id: 'contemporary_satellite',
    name: 'Contemporain (Imagerie Satellitaire Esri & Hybride Vectoriel)',
    era: '2024',
    mode: 'both',
    bearing: 0,
    bordersVisibleByDefault: true,
    mapStyleUrl: 'https://basemaps.cartocdn.com/gl/voyager-gl-style/style.json',
    texture: {
      blendMode: 'multiply',
      opacity: 0,
    },
    fontFamily: '"Inter", "Helvetica Neue", sans-serif',
    decorativeBorder: null,
    labelLanguage: 'fr',
    mapPaintOverrides: {
      borderColor: '#f59e0b',
    },
  },
  {
    id: 'nasa_night_lights',
    name: 'Contemporain (NASA Vue Nocturne — Black Marble)',
    era: '2024',
    mode: 'both',
    bearing: 0,
    bordersVisibleByDefault: true,
    mapStyleUrl: 'https://basemaps.cartocdn.com/gl/dark-matter-gl-style/style.json',
    texture: {
      blendMode: 'screen',
      opacity: 0,
    },
    fontFamily: '"Inter", "Helvetica Neue", sans-serif',
    decorativeBorder: null,
    labelLanguage: 'fr',
    mapPaintOverrides: {
      borderColor: '#f59e0b',
    },
  },
  {
    id: 'contemporary_national_geographic',
    name: 'Contemporain (National Geographic — Atlas Physique)',
    era: '2024',
    mode: 'both',
    bearing: 0,
    bordersVisibleByDefault: true,
    mapStyleUrl: 'https://basemaps.cartocdn.com/gl/positron-gl-style/style.json',
    texture: {
      blendMode: 'multiply',
      opacity: 0.15,
    },
    fontFamily: '"Cinzel", "Garamond", "Georgia", serif',
    decorativeBorder: null,
    labelLanguage: 'fr',
    mapPaintOverrides: {
      background: '#fef3c7',
      water: '#0f172a',
      landcover: '#fde68a',
    },
  },
  {
    id: 'contemporary_positron_lite',
    name: 'Contemporain (Dark Slate — Mode Sombre Tactique)',
    era: '2024',
    mode: 'both',
    bearing: 0,
    bordersVisibleByDefault: true,
    mapStyleUrl: 'https://basemaps.cartocdn.com/gl/dark-matter-gl-style/style.json',
    texture: {
      blendMode: 'multiply',
      opacity: 0,
    },
    fontFamily: '"Inter", "Helvetica Neue", sans-serif',
    decorativeBorder: null,
    labelLanguage: 'fr',
    mapPaintOverrides: {
      background: '#1e293b',
      water: '#070f1e',
      landcover: '#334155',
      borderColor: '#38bdf8',
    },
  },
  {
    id: 'journalism_electro_80s',
    name: 'Journalisme Électro-Futuriste (Années 1980 — Synthwave CRT)',
    era: '1980',
    mode: 'both',
    bearing: 0,
    bordersVisibleByDefault: true,
    mapStyleUrl: 'https://basemaps.cartocdn.com/gl/dark-matter-gl-style/style.json',
    texture: {
      blendMode: 'screen',
      opacity: 0.15,
      borderColor: '#ec4899',
      borderWidth: 3,
    },
    scanlines: {
      enabled: true,
      speed: 2,
      opacity: 0.25,
      color: '#06b6d4',
    },
    fontFamily: '"VT323", "Courier New", monospace',
    decorativeBorder: null,
    labelLanguage: 'fr',
    mapPaintOverrides: {
      background: '#1e1b4b',
      water: '#2e1065',
      landcover: '#2e1065',
      borderColor: '#ec4899',
    },
  },
  {
    id: 'cnn_broadcast_90s_00s',
    name: 'Carte CNN Broadcast (Années 1990–2000 — TV News 24h)',
    era: '1990–2000',
    mode: 'both',
    bearing: 0,
    bordersVisibleByDefault: true,
    mapStyleUrl: 'https://basemaps.cartocdn.com/gl/voyager-gl-style/style.json',
    texture: {
      blendMode: 'multiply',
      opacity: 0,
      borderColor: '#f59e0b',
      borderWidth: 3,
    },
    fontFamily: '"Impact", "Trebuchet MS", "Arial Black", sans-serif',
    decorativeBorder: null,
    labelLanguage: 'fr',
    mapPaintOverrides: {
      background: '#15803d',
      water: '#030f26',
      landcover: '#166534',
      borderColor: '#f59e0b',
    },
  },
];
