// core/styles/realStylesHistorical.ts

import type { StyleConfig } from '../styles.config';

export const HISTORICAL_STYLE_CONFIGS: StyleConfig[] = [
  {
    id: 'antiquity',
    name: 'Antiquité (Tabula Peutingeriana)',
    era: 'IVe–Ve siècle',
    mode: 'both',
    bearing: 0,
    bordersVisibleByDefault: false,
    mapStyleUrl: 'https://basemaps.cartocdn.com/gl/positron-gl-style/style.json',
    texture: {
      blendMode: 'multiply',
      opacity: 0.35,
      svgFilterId: 'parchment-coarse',
      radialVignette: { inner: 'transparent', outer: 'rgba(101,67,33,0.5)' },
      noisePattern: { frequency: 0.04, octaves: 4 },
      borderColor: '#8B5A2B',
      borderWidth: 6,
    },
    deformation: { scaleY: 0.3, overflow: 'scroll' },
    fontFamily: '"Cinzel", "Times New Roman", serif',
    decorativeBorder: 'crane',
    labelLanguage: 'la',
    mapPaintOverrides: {
      background: '#fff7ed',
      water: '#047857',
      landcover: '#fed7aa',
    },
  },
  {
    id: 'military_staff_ww1_ww2',
    name: 'Carte d\'État-Major (Guerres Mondiales 1914–1945)',
    era: '1914–1945',
    mode: 'both',
    bearing: 0,
    bordersVisibleByDefault: true,
    mapStyleUrl: 'https://basemaps.cartocdn.com/gl/positron-gl-style/style.json',
    texture: {
      blendMode: 'multiply',
      opacity: 0.3,
      svgFilterId: 'paper-heavy',
      borderColor: '#334155',
      borderWidth: 4,
    },
    graticule: {
      enabled: true,
      step: 10,
      color: '#991b1b',
      opacity: 0.4,
      labelColor: '#991b1b',
    },
    fontFamily: '"Courier New", "Courier", monospace',
    decorativeBorder: null,
    labelLanguage: 'fr',
    mapPaintOverrides: {
      background: '#f1f1e6',
      water: '#94a3b8',
      landcover: '#d8d4ab',
    },
  },
  {
    id: 'journalism_60s_70s',
    name: 'Presse & Journalisme (Années 1960–1970)',
    era: '1960–1970',
    mode: 'both',
    bearing: 0,
    bordersVisibleByDefault: true,
    mapStyleUrl: 'https://basemaps.cartocdn.com/gl/positron-gl-style/style.json',
    texture: {
      blendMode: 'multiply',
      opacity: 0.25,
      svgFilterId: 'paper-smooth',
      borderColor: '#18181b',
      borderWidth: 3,
    },
    fontFamily: '"Georgia", "Times New Roman", serif',
    decorativeBorder: null,
    labelLanguage: 'fr',
    mapPaintOverrides: {
      background: '#f4ebd9',
      water: '#64748b',
      landcover: '#e5d9b6',
    },
  },
  {
    id: 'medieval',
    name: 'Moyen Âge (Portulan Catalan)',
    era: '1375',
    mode: 'both',
    bearing: 0,
    bordersVisibleByDefault: false,
    mapStyleUrl: 'https://basemaps.cartocdn.com/gl/positron-gl-style/style.json',
    texture: {
      blendMode: 'multiply',
      opacity: 0.4,
      svgFilterId: 'parchment-fine',
      radialVignette: { inner: 'transparent', outer: 'rgba(74,48,24,0.45)' },
      noisePattern: { frequency: 0.02, octaves: 3 },
      borderColor: '#7A4A20',
      borderWidth: 4,
    },
    rhumbLines: {
      enabled: true,
      centers: [[12.5, 42.0], [3.0, 39.5], [24.0, 38.0], [-9.0, 38.7]],
      rayCount: 16,
      colors: ['#8B0000', '#000080', '#000000', '#DAA520'],
      radiusKm: 2500,
      lineWidth: 0.8,
      labels: ['Tramontana', 'Greco', 'Levante', 'Scirocco', 'Ostria', 'Libeccio', 'Ponente', 'Maestro'],
    },
    fontFamily: '"UnifrakturMaguntia", "Georgia", serif',
    decorativeBorder: 'rinceaux',
    labelLanguage: 'la',
    mapPaintOverrides: {
      background: '#f1e6d0',
      water: '#c4d8e2',
      landcover: '#e5d7bc',
    },
  },
  {
    id: 'renaissance',
    name: 'Renaissance (Atlas Maior Blaeu)',
    era: '1662',
    mode: 'both',
    bearing: 0,
    bordersVisibleByDefault: false,
    mapStyleUrl: 'https://basemaps.cartocdn.com/gl/positron-gl-style/style.json',
    texture: {
      blendMode: 'multiply',
      opacity: 0.3,
      svgFilterId: 'paper-heavy',
      radialVignette: { inner: 'transparent', outer: 'rgba(90,60,30,0.35)' },
      borderColor: '#B8860B',
      borderWidth: 8,
    },
    rhumbLines: {
      enabled: true,
      centers: [[0, 50], [15, 45]],
      rayCount: 16,
      colors: ['#B8860B', '#2E8B57', '#8B0000', '#191970'],
      radiusKm: 3000,
      lineWidth: 0.6,
    },
    fontFamily: '"IM Fell English", "Georgia", serif',
    decorativeBorder: 'baroque',
    labelLanguage: 'la',
    mapPaintOverrides: {
      background: '#f7f2e8',
      water: '#d0e1e8',
      landcover: '#e8dfcb',
    },
  },
  {
    id: 'modern',
    name: 'Époque Moderne (Carte de Cassini)',
    era: 'XVIIIe siècle',
    mode: 'both',
    bearing: 0,
    bordersVisibleByDefault: false,
    mapStyleUrl: 'https://basemaps.cartocdn.com/gl/positron-gl-style/style.json',
    texture: {
      blendMode: 'multiply',
      opacity: 0.25,
      svgFilterId: 'paper-smooth',
      radialVignette: { inner: 'transparent', outer: 'rgba(60,40,20,0.25)' },
      borderColor: '#555555',
      borderWidth: 3,
    },
    engravingFilter: true,
    fontFamily: '"Baskerville", "Garamond", serif',
    decorativeBorder: null,
    labelLanguage: 'fr',
    mapPaintOverrides: {
      background: '#faf6ee',
      water: '#d8e4eb',
      landcover: '#eee6d4',
    },
  },
  {
    id: 'al_idrisi',
    name: 'Moyen Âge Islamique (Tabula Rogeriana — Al-Idrisi)',
    era: '1154',
    mode: 'both',
    bearing: 180,
    bordersVisibleByDefault: false,
    mapStyleUrl: 'https://basemaps.cartocdn.com/gl/positron-gl-style/style.json',
    texture: {
      blendMode: 'multiply',
      opacity: 0.45,
      svgFilterId: 'parchemin-gold',
      radialVignette: { inner: 'transparent', outer: 'rgba(120,80,20,0.5)' },
      borderColor: '#B8860B',
      borderWidth: 6,
    },
    rhumbLines: {
      enabled: true,
      centers: [[14.0, 37.5], [32.5, 25.0]],
      rayCount: 16,
      colors: ['#DAA520', '#1D65A6', '#B84028', '#2E8B57'],
      radiusKm: 2800,
      lineWidth: 0.8,
      labels: ['Janūb (Sud)', 'Shamāl (Nord)', 'Sharq (Est)', 'Gharb (Ouest)'],
    },
    fontFamily: '"Amiri", "Traditional Arabic", "Georgia", serif',
    decorativeBorder: 'rinceaux',
    labelLanguage: 'ar',
    mapPaintOverrides: {
      background: '#e6d5ac',
      water: '#1d65a6',
      landcover: '#f0e2b6',
    },
  },
  {
    id: 'military_tactical_wargames',
    name: 'Tactique Guerre Froide (WarGames NORAD WOPR — 1983)',
    era: '1983',
    mode: 'both',
    bearing: 0,
    bordersVisibleByDefault: true,
    mapStyleUrl: 'https://basemaps.cartocdn.com/gl/dark-matter-gl-style/style.json',
    texture: {
      blendMode: 'screen',
      opacity: 0.2,
      borderColor: '#22c55e',
      borderWidth: 4,
    },
    scanlines: {
      enabled: true,
      speed: 3,
      opacity: 0.35,
      color: '#22c55e',
    },
    graticule: {
      enabled: true,
      step: 10,
      color: '#22c55e',
      opacity: 0.3,
      labelColor: '#f59e0b',
    },
    fontFamily: '"Courier New", "VT323", monospace',
    decorativeBorder: null,
    labelLanguage: 'en',
    mapPaintOverrides: {
      background: '#020617',
      water: '#020617',
      landcover: '#14532d',
    },
  },
];
