// core/styles/realStylesHistorical.ts

import type { StyleConfig } from '../styles.config';

export const HISTORICAL_STYLE_CONFIGS: StyleConfig[] = [
  {
    id: 'antiquity',
    name: 'Antiquité (Tabula Peutingeriana)',
    era: 'IVe–Ve siècle',
    mode: 'both',
    bearing: 0,
    bordersVisibleByDefault: false,
    mapStyleUrl: 'https://basemaps.cartocdn.com/gl/positron-gl-style/style.json',
    texture: {
      blendMode: 'multiply',
      opacity: 0.35,
      svgFilterId: 'parchment-coarse',
      radialVignette: { inner: 'transparent', outer: 'rgba(101,67,33,0.5)' },
      noisePattern: { frequency: 0.04, octaves: 4 },
      borderColor: '#8B5A2B',
      borderWidth: 6,
    },
    deformation: { scaleY: 0.3, overflow: 'scroll' },
    fontFamily: '"Cinzel", "Times New Roman", serif',
    decorativeBorder: 'crane',
    labelLanguage: 'la',
    mapPaintOverrides: {
      background: '#fff7ed',
      water: '#047857',
      landcover: '#fed7aa',
    },
  },
  {
    id: 'military_staff_ww1_ww2',
    name: 'Carte d\'État-Major (Guerres Mondiales 1914–1945)',
    era: '1914–1945',
    mode: 'both',
    bearing: 0,
    bordersVisibleByDefault: true,
    mapStyleUrl: 'https://basemaps.cartocdn.com/gl/positron-gl-style/style.json',
    texture: {
      blendMode: 'multiply',
      opacity: 0.3,
      svgFilterId: 'paper-heavy',
      borderColor: '#334155',
      borderWidth: 4,
    },
    graticule: {
      enabled: false,
      step: 10,
      color: '#991b1b',
      opacity: 0.4,
      labelColor: '#991b1b',
    },
    fontFamily: '"Courier New", "Courier", monospace',
    decorativeBorder: null,
    labelLanguage: 'fr',
    mapPaintOverrides: {
      background: '#f1f1e6',
      water: '#94a3b8',
      landcover: '#d8d4ab',
    },
  },
  {
    id: 'journalism_60s_70s',
    name: 'Presse & Journalisme (Années 1960–1970)',
    era: '1960–1970',
    mode: 'both',
    bearing: 0,
    bordersVisibleByDefault: true,
    mapStyleUrl: 'https://basemaps.cartocdn.com/gl/positron-gl-style/style.json',
    texture: {
      blendMode: 'multiply',
      opacity: 0.25,
      svgFilterId: 'paper-smooth',
      borderColor: '#18181b',
      borderWidth: 3,
    },
    fontFamily: '"Georgia", "Times New Roman", serif',
    decorativeBorder: null,
    labelLanguage: 'fr',
    mapPaintOverrides: {
      background: '#f4ebd9',
      water: '#64748b',
      landcover: '#e5d9b6',
    },
  },
  {
    id: 'medieval',
    name: 'Moyen Âge (Portulan Catalan)',
    era: '1375',
    mode: 'both',
    bearing: 0,
    bordersVisibleByDefault: false,
    mapStyleUrl: 'https://basemaps.cartocdn.com/gl/positron-gl-style/style.json',
    texture: {
      blendMode: 'multiply',
      opacity: 0.4,
      svgFilterId: 'parchment-fine',
      radialVignette: { inner: 'transparent', outer: 'rgba(74,48,24,0.45)' },
      noisePattern: { frequency: 0.02, octaves: 3 },
      borderColor: '#7A4A20',
      borderWidth: 4,
    },
    rhumbLines: {
      enabled: false,
      preset: 'medieval',
      labels: ['Tramontana', 'Greco', 'Levante', 'Scirocco', 'Ostria', 'Libeccio', 'Ponente', 'Maestro'],
    },
    fontFamily: '"UnifrakturMaguntia", "Georgia", serif',
    decorativeBorder: 'rinceaux',
    labelLanguage: 'la',
    mapPaintOverrides: {
      background: '#f1e6d0',
      water: '#c4d8e2',
      landcover: '#e5d7bc',
    },
  },
  {
    id: 'renaissance',
    name: 'Renaissance (Atlas Maior Blaeu)',
    era: '1662',
    mode: 'both',
    bearing: 0,
    bordersVisibleByDefault: false,
    mapStyleUrl: 'https://basemaps.cartocdn.com/gl/positron-gl-style/style.json',
    texture: {
      blendMode: 'multiply',
      opacity: 0.3,
      svgFilterId: 'paper-heavy',
      radialVignette: { inner: 'transparent', outer: 'rgba(90,60,30,0.35)' },
      borderColor: '#B8860B',
      borderWidth: 8,
    },
    rhumbLines: {
      enabled: false,
      preset: 'renaissance',
    },
    fontFamily: '"IM Fell English", "Georgia", serif',
    decorativeBorder: 'baroque',
    labelLanguage: 'la',
    mapPaintOverrides: {
      background: '#f7f2e8',
      water: '#d0e1e8',
      landcover: '#e8dfcb',
    },
  },
  {
    id: 'modern',
    name: 'Époque Moderne (Carte de Cassini)',
    era: 'XVIIIe siècle',
    mode: 'both',
    bearing: 0,
    bordersVisibleByDefault: false,
    mapStyleUrl: 'https://basemaps.cartocdn.com/gl/positron-gl-style/style.json',
    texture: {
      blendMode: 'multiply',
      opacity: 0.25,
      svgFilterId: 'paper-smooth',
      radialVignette: { inner: 'transparent', outer: 'rgba(60,40,20,0.25)' },
      borderColor: '#555555',
      borderWidth: 3,
    },
    engravingFilter: true,
    fontFamily: '"Baskerville", "Garamond", serif',
    decorativeBorder: null,
    labelLanguage: 'fr',
    mapPaintOverrides: {
      background: '#faf6ee',
      water: '#d8e4eb',
      landcover: '#eee6d4',
    },
  },
  {
    id: 'al_idrisi',
    name: 'Moyen Âge Islamique (Tabula Rogeriana — Al-Idrisi)',
    era: '1154',
    mode: 'both',
    bearing: 180,
    bordersVisibleByDefault: false,
    mapStyleUrl: 'https://basemaps.cartocdn.com/gl/positron-gl-style/style.json',
    texture: {
      blendMode: 'multiply',
      opacity: 0.45,
      svgFilterId: 'parchemin-gold',
      radialVignette: { inner: 'transparent', outer: 'rgba(120,80,20,0.5)' },
      borderColor: '#B8860B',
      borderWidth: 6,
    },
    rhumbLines: {
      enabled: false,
      preset: 'medieval',
      labels: ['Janūb (Sud)', 'Shamāl (Nord)', 'Sharq (Est)', 'Gharb (Ouest)'],
    },
    fontFamily: '"Amiri", "Traditional Arabic", "Georgia", serif',
    decorativeBorder: 'rinceaux',
    labelLanguage: 'ar',
    mapPaintOverrides: {
      background: '#e6d5ac',
      water: '#1d65a6',
      landcover: '#f0e2b6',
    },
  },
  {
    id: 'jules_verne',
    name: 'Voyages Extraordinaires (Jules Verne — Hetzel 1889)',
    era: '1889',
    mode: 'both',
    bearing: 0,
    bordersVisibleByDefault: false,
    mapStyleUrl: 'https://basemaps.cartocdn.com/gl/positron-gl-style/style.json',
    texture: {
      blendMode: 'multiply',
      opacity: 0.38,
      svgFilterId: 'paper-heavy',
      radialVignette: { inner: 'transparent', outer: 'rgba(74,48,24,0.45)' },
      borderColor: '#5c3d24',
      borderWidth: 6,
    },
    engravingFilter: true,
    rhumbLines: {
      enabled: false,
      preset: 'renaissance',
      labels: ['Nord', 'Nord-Est', 'Est', 'Sud-Est', 'Sud', 'Sud-Ouest', 'Ouest', 'Nord-Ouest'],
    },
    graticule: {
      enabled: false,
      step: 10,
      color: '#7a5a3a',
      opacity: 0.45,
      labelColor: '#5c3d24',
    },
    fontFamily: '"IM Fell English", "Playfair Display", "Georgia", serif',
    decorativeBorder: 'baroque',
    labelLanguage: 'fr',
    mapPaintOverrides: {
      background: '#f4ece1',
      water: '#4e736b',
      landcover: '#e8deb8',
      borderColor: '#5c3d24',
    },
  },
  {
    id: 'twentieth_century_physical',
    name: 'Relief Classique XXe Siècle (Atlas Hypsométrique)',
    era: 'XXe siècle',
    mode: 'both',
    bearing: 0,
    bordersVisibleByDefault: true,
    mapStyleUrl: 'https://basemaps.cartocdn.com/gl/positron-gl-style/style.json',
    texture: {
      blendMode: 'multiply',
      opacity: 0.15,
      borderColor: '#3b6e8c',
      borderWidth: 4,
    },
    demEnabled: true,
    demExaggeration: 1.6,
    graticule: {
      enabled: false,
      step: 10,
      color: '#3b6e8c',
      opacity: 0.4,
      labelColor: '#1d4863',
    },
    fontFamily: '"Roboto", "Helvetica Neue", "Arial", sans-serif',
    decorativeBorder: null,
    labelLanguage: 'fr',
    mapPaintOverrides: {
      background: '#94d17b',
      water: '#7ac5e3',
      landcover: '#dce897',
      borderColor: '#2b4c5e',
      hillshadeShadow: '#6e2b14',
      hillshadeHighlight: '#fdf6e7',
      hillshadeAccent: '#8c421a',
      hillshadeExaggeration: 0.95,
    },
  },
  {
    id: 'military_tactical_wargames',
    name: 'Tactique Guerre Froide (WarGames NORAD WOPR — 1983)',
    era: '1983',
    mode: 'both',
    bearing: 0,
    bordersVisibleByDefault: true,
    mapStyleUrl: 'https://basemaps.cartocdn.com/gl/dark-matter-gl-style/style.json',
    texture: {
      blendMode: 'screen',
      opacity: 0.2,
      borderColor: '#22c55e',
      borderWidth: 4,
    },
    scanlines: {
      enabled: true,
      speed: 3,
      opacity: 0.35,
      color: '#22c55e',
    },
    graticule: {
      enabled: false,
      step: 10,
      color: '#22c55e',
      opacity: 0.3,
      labelColor: '#f59e0b',
    },
    fontFamily: '"Courier New", "VT323", monospace',
    decorativeBorder: null,
    labelLanguage: 'en',
    mapPaintOverrides: {
      background: '#040d1a',
      water: '#07182c',
      landcover: '#0d381e',
      borderColor: '#22c55e',
    },
  },
];
