// app/state/storeTypes.ts

import { DatabaseSchema } from '../../core/schema';
import { BasemapStyleId } from '../../core/styles.config';

export type ViewMode = '2D' | '3D' | 'timeline' | 'network' | 'split';

export interface AppState {
  world: DatabaseSchema;
  worldsList: any[];
  isLoading: boolean;
  isFirstLoadDone: boolean;
  selectedEntityId: string | null;
  wikiModalEntityId: string | null;
  basemapStyle: BasemapStyleId;
  basemapLabelsVisible: boolean;
  basemapBordersVisible: boolean;
  basemapRoadsVisible: boolean;
  basemapRiversVisible: boolean;
  geoReferenceLinesVisible: boolean;
  portulanRhumbVisible: boolean;
  graticuleVisible: boolean;
  mapProjection: 'mercator' | 'globe';
  activeEmpire: 'all' | 'british' | 'french' | 'portuguese' | 'neutral';
  currentTime: number;
  startYear: number;
  endYear: number;
  viewMode: ViewMode;
  isPlaying: boolean;
  playbackSpeed: number;
  prometheanMode: boolean;
  mapLoading: boolean;
  mapLoadingProgress: number;
  mapLoadingDuration: number;
  networkFilters: any;
  aiProposals: any[];
  aiSessions: any[];
  selectedProposal: any | null;
  importLoading: boolean;
  exportLoading: boolean;
  importError: string | null;
  exportError: string | null;
  importProgress: { current: number; total: number; title: string } | null;
  climateSeaLevelVisible: boolean;
  climateIceCapVisible: boolean;
  climateMedianTarget: number;
  climateRcpVariability: boolean;
  climateSelectedRcp: 'RCP2.6' | 'RCP4.5' | 'RCP6.0' | 'RCP8.5' | null;
  tolkienClimateParams: any;

  saveToDB: () => Promise<void>;
  initFromDB: (worldId?: string) => Promise<void>;
  createRealWorld: (name: string, description?: string, basemapStyle?: BasemapStyleId, startYear?: number, endYear?: number) => Promise<string>;
  createFictionalWorld: (name: string, description?: string, startYear?: number, endYear?: number) => Promise<string>;
  createNewWorld: (name: string, description?: string, type?: 'real' | 'fictional', basemapStyle?: BasemapStyleId, startYear?: number, endYear?: number) => Promise<string>;
  deleteWorld: (worldId: string) => Promise<void>;
  duplicateWorld: (worldId: string, newName: string) => Promise<void>;
  saveContinents: (geojson: any) => Promise<void>;
  setSelectedEntity: (id: string | null) => void;
  setWikiModalEntityId: (id: string | null) => void;
  addLayer: (name: string, type: 'physical' | 'political' | 'economic' | 'social' | 'cultural' | 'historical') => void;
  toggleLayerVisibility: (layerId: string) => void;
  removeLayer: (layerId: string) => void;
  addEntity: (layerId: string, name: string, type?: 'place' | 'event' | 'actor' | 'concept', validFrom?: number, validTo?: number) => string;
  updateEntity: (entityId: string, updates: Partial<any>) => void;
  updateEntityGeometry: (entityId: string, geometry: any) => void;
  updateEntityTemporalRange: (entityId: string, validFrom?: number, validTo?: number) => void;
  updateEntityProperties: (entityId: string, properties: Record<string, any>) => void;
  updateEntityWikiContent: (entityId: string, wikiContent: string) => void;
  clearEntityGeometry: (entityId: string) => void;
  removeEntity: (entityId: string) => void;
  addRelation: (sourceId: string, targetId: string, type: string, direction?: 'directed' | 'undirected' | 'bidirectional', weight?: number, isSpatial?: boolean, entityId?: string, validFrom?: number, validTo?: number) => void;
  removeRelation: (relationId: string) => void;
  setBasemapStyle: (style: BasemapStyleId) => void;
  setBasemapLabelsVisible: (visible: boolean) => void;
  setBasemapBordersVisible: (visible: boolean) => void;
  setBasemapRoadsVisible: (visible: boolean) => void;
  setBasemapRiversVisible: (visible: boolean) => void;
  setGeoReferenceLinesVisible: (visible: boolean) => void;
  setPortulanRhumbVisible: (visible: boolean) => void;
  setGraticuleVisible: (visible: boolean) => void;
  setMapProjection: (projection: 'mercator' | 'globe') => void;
  setActiveEmpire: (empire: 'all' | 'british' | 'french' | 'portuguese' | 'neutral') => void;
  setCurrentTime: (time: number) => void;
  setViewMode: (mode: ViewMode) => void;
  togglePlayback: () => void;
  setPlaybackSpeed: (speed: number) => void;
  togglePrometheanMode: () => void;
  updateReliefStyle: (exaggeration: number, shadowColor: string, highlightColor: string) => void;
  setMapLoading: (loading: boolean, durationMs?: number) => void;
  setMapLoadingProgress: (progress: number) => void;
  setFirstLoadDone: (done: boolean) => void;
  setClimateSeaLevelVisible: (visible: boolean) => void;
  setClimateIceCapVisible: (visible: boolean) => void;
  setClimateMedianTarget: (target: number) => void;
  setClimateRcpVariability: (enabled: boolean) => void;
  setClimateSelectedRcp: (rcp: 'RCP2.6' | 'RCP4.5' | 'RCP6.0' | 'RCP8.5' | null) => void;
  setTolkienClimateParams: (params: any) => void;
  setNetworkFilters: (filters: any) => void;
  addAiProposal: (proposal: any) => void;
  acceptAiProposal: (proposalId: string) => Promise<void>;
  rejectAiProposal: (proposalId: string, reason?: string) => void;
  toggleProposalSubEntity: (proposalId: string, subId: string) => void;
  addSubEntityToProposal: (proposalId: string, name: string, type: string, geometry?: any) => void;
  updateSubEntityInProposal: (proposalId: string, subId: string, updates: Partial<any>) => void;
  removeSubEntityFromProposal: (proposalId: string, subId: string) => void;
  selectProposal: (proposal: any | null) => void;
  addAiSession: (session: any) => void;
  exportWorld: () => Promise<void>;
  importWorldFile: (file: File) => Promise<string>;
  importBatchEntities: (entities: any[], batchTitle?: string) => Promise<void>;
  rollbackImportBatch: (importBatchId: string) => Promise<number>;
  clearErrors: () => void;
}
